/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/usuarios/{usuario_id}/resetar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resetar Senha Admin
         * @description PRD US 1.10 — invalida a senha atual, envia link de redefinição, audita.
         */
        post: operations["resetar_senha_admin_admin_usuarios__usuario_id__resetar_senha_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/primeiro-acesso/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Primeiro Acesso
         * @description PRD US 1.6 Cen.1 — senha aceita, usuário é autenticado e status vira Ativo.
         */
        post: operations["primeiro_acesso_auth_primeiro_acesso__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recuperar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recuperar Senha
         * @description PRD US 1.3 Cen.3/Cen.5 — nunca revela se o e-mail está cadastrado.
         */
        post: operations["recuperar_senha_auth_recuperar_senha_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/redefinir-senha/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redefinir Senha
         * @description Zera bloqueio/tentativas na mesma transação (US 1.3 Cen.2c — desbloqueio automático).
         */
        post: operations["redefinir_senha_auth_redefinir_senha__token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/trocar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trocar Senha
         * @description PRD US 1.7 — exige senha atual correta; impede reuso das últimas 6 senhas.
         */
        post: operations["trocar_senha_auth_trocar_senha_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/dev/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Emails */
        get: operations["listar_emails_internal_dev_emails_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/dev/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resetar */
        post: operations["resetar_internal_dev_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/tasks/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Email Task
         * @description Processa uma tarefa de e-mail entregue pelo Cloud Tasks.
         *
         *     Contrato de falha (US 5.2 Cen.3): em QUALQUER falha de entrega, registra em
         *     log e retorna 200 (ACK). A fila usa maxAttempts=1, então não há redespacho.
         *     Nunca propaga exceção — isso faria o Cloud Tasks tratar como retryable.
         */
        post: operations["process_email_task_internal_tasks_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Kanban
         * @description US 2.3/2.8 — Kanban da unidade (Servidor) ou consolidado (Gestor).
         */
        get: operations["listar_kanban_processos_get"];
        put?: never;
        /**
         * Criar Processo
         * @description US 2.1 — Servidor cria processo na própria unidade.
         */
        post: operations["criar_processo_processos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processos/busca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Processos
         * @description US 2.7 — busca interna restrita ao escopo de unidade.
         */
        get: operations["buscar_processos_processos_busca_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processos/{processo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalhe Processo
         * @description US 1.4 Cen.2 — detalhe por unidade; acesso fora do escopo é negado e logado.
         */
        get: operations["detalhe_processo_processos__processo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processos/{processo_id}/despachar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Despachar Processo
         * @description US 2.2 — despacho para a próxima unidade; na última, conclusão confirmada.
         */
        post: operations["despachar_processo_processos__processo_id__despachar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processos/{processo_id}/devolver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Devolver Processo
         * @description US 2.2b — devolução para a unidade anterior, com motivo obrigatório.
         */
        post: operations["devolver_processo_processos__processo_id__devolver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/processos/{processo_id}/historico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historico Processo
         * @description US 2.4 — linha do tempo imutável; vazia para processo recém-criado.
         */
        get: operations["historico_processo_processos__processo_id__historico_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicializar Sistema */
        post: operations["inicializar_sistema_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status Inicializacao */
        get: operations["status_inicializacao_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tipos-processo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Tipos Processo
         * @description Catálogo de tipos de processo com o roteiro vigente de cada um.
         *
         *     Leitura aberta a qualquer usuário autenticado (Servidor precisa listar o
         *     catálogo para criar processo — US 2.1); cadastro/edição de roteiro
         *     permanecem admin-only (US 8.2, `_require_admin` abaixo).
         */
        get: operations["listar_tipos_processo_tipos_processo_get"];
        put?: never;
        /** Criar Tipo Processo */
        post: operations["criar_tipo_processo_tipos_processo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tipos-processo/{tipo_processo_id}/roteiro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Atualizar Roteiro
         * @description US 8.2 Cen.2 — cria nova versão vigente; a anterior fica congelada
         *     (`vigente=false`) e suas `roteiro_etapa` nunca são alteradas — processos já
         *     criados sob ela mantêm o roteiro do momento de sua criação.
         */
        put: operations["atualizar_roteiro_tipos_processo__tipo_processo_id__roteiro_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Unidades
         * @description Catálogo de unidades — usado pelos formulários de cadastro/CRUD do frontend.
         */
        get: operations["listar_unidades_unidades_get"];
        put?: never;
        /** Cadastrar Unidade */
        post: operations["cadastrar_unidade_unidades_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{unidade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar Unidade */
        patch: operations["editar_unidade_unidades__unidade_id__patch"];
        trace?: never;
    };
    "/unidades/{unidade_id}/desativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desativar Unidade */
        post: operations["desativar_unidade_unidades__unidade_id__desativar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Usuarios
         * @description Administrador lista todos; Gestor só lista usuários das unidades que gerencia.
         */
        get: operations["listar_usuarios_usuarios_get"];
        put?: never;
        /**
         * Cadastrar Usuario
         * @description PRD US 1.1 (Administrador) e US 1.2 (Gestor, restrito à própria unidade/perfil Servidor).
         */
        post: operations["cadastrar_usuario_usuarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/me/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meu Perfil
         * @description US 1.5 — sempre os dados do próprio token (`get_current_user`); não há
         *     parâmetro de ID manipulável, então não existe rota que permita ver o
         *     perfil de terceiros (US 1.5 Cen.2 / task 10.2). A lista de processos atuados
         *     (Cen.1) acompanha o usuário mesmo após transferência (US 1.4 Cen.3).
         */
        get: operations["meu_perfil_usuarios_me_perfil_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{usuario_id}/unidade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transferir Unidade
         * @description US 8.6 — vínculo 1:1 Servidor↔unidade. O PATCH sempre *substitui* o
         *     vínculo (nunca adiciona), então o cenário de "vínculo duplo" (Cen.2) é
         *     estruturalmente impossível: não existe operação que preserve o vínculo
         *     anterior e crie um segundo — `unidade_id` é uma FK escalar.
         */
        patch: operations["transferir_unidade_usuarios__usuario_id__unidade_patch"];
        trace?: never;
    };
    "/usuarios/{usuario_id}/unidades-geridas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Unidades Geridas */
        get: operations["obter_unidades_geridas_usuarios__usuario_id__unidades_geridas_get"];
        /**
         * Definir Unidades Geridas
         * @description US 8.6b — conjunto de unidades geridas por um Gestor (N:N).
         */
        put: operations["definir_unidades_geridas_usuarios__usuario_id__unidades_geridas_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckResponse */
        AckResponse: {
            /**
             * Status
             * @example acked
             */
            status: string;
        };
        /** AtualizarRoteiroRequest */
        AtualizarRoteiroRequest: {
            /** Unidade Ids */
            unidade_ids?: string[];
        };
        /** CadastroUnidadeRequest */
        CadastroUnidadeRequest: {
            /** Gestor Responsavel Id */
            gestor_responsavel_id?: string | null;
            /** Nome */
            nome: string;
            /** Sigla */
            sigla: string;
        };
        /** CadastroUsuarioRequest */
        CadastroUsuarioRequest: {
            /** Email */
            email: string;
            /** Nome */
            nome: string;
            /**
             * Perfil
             * @enum {string}
             */
            perfil: "servidor" | "gestor" | "administrador";
            /** Unidade Id */
            unidade_id?: string | null;
        };
        /**
         * CardProcessoResponse
         * @description Card enxuto do Kanban/busca (US 2.3, 2.7, 2.8).
         */
        CardProcessoResponse: {
            /** Assunto */
            assunto: string;
            /** Dias Restantes */
            dias_restantes: number;
            /** Id */
            id: string;
            /** Numero */
            numero: string;
            /**
             * Prazo Em
             * Format: date
             */
            prazo_em: string;
            /** Status */
            status: string;
            /** Unidade Atual Id */
            unidade_atual_id: string;
            /** Vencido */
            vencido: boolean;
        };
        /** CriarProcessoRequest */
        CriarProcessoRequest: {
            /** Assunto */
            assunto: string;
            /** Interessados */
            interessados?: components["schemas"]["InteressadoInput"][];
            /** Prazo Dias */
            prazo_dias: number;
            /** Tipo Processo Id */
            tipo_processo_id: string;
        };
        /** CriarTipoProcessoRequest */
        CriarTipoProcessoRequest: {
            /** Nome */
            nome: string;
            /** Unidade Ids */
            unidade_ids?: string[];
        };
        /** DespacharRequest */
        DespacharRequest: {
            /**
             * Confirmar
             * @default false
             */
            confirmar: boolean;
        };
        /** DevEmailItem */
        DevEmailItem: {
            /** Body */
            body: string;
            /** Event Id */
            event_id: string;
            /** Subject */
            subject: string;
            /** To */
            to: string;
        };
        /** DevolverRequest */
        DevolverRequest: {
            /** Justificativa */
            justificativa?: string | null;
            /** Motivo */
            motivo?: string | null;
        };
        /** EditarUnidadeRequest */
        EditarUnidadeRequest: {
            /** Gestor Responsavel Id */
            gestor_responsavel_id?: string | null;
            /** Nome */
            nome?: string | null;
            /** Sigla */
            sigla?: string | null;
        };
        /**
         * EmailTaskPayload
         * @description Corpo da tarefa enfileirada no Cloud Tasks e entregue ao endpoint interno.
         */
        EmailTaskPayload: {
            /** Body */
            body: string;
            /** Event Id */
            event_id: string;
            /** Subject */
            subject: string;
            /**
             * To
             * Format: email
             */
            to: string;
        };
        /** EtapaRoteiroResponse */
        EtapaRoteiroResponse: {
            /** Ordem */
            ordem: number;
            /** Unidade Id */
            unidade_id: string;
        };
        /** EventoHistoricoResponse */
        EventoHistoricoResponse: {
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Id */
            id: string;
            /** Justificativa */
            justificativa: string | null;
            /** Motivo */
            motivo: string | null;
            /** Responsavel Id */
            responsavel_id: string;
            /** Status Resultante */
            status_resultante: string;
            /** Tipo Evento */
            tipo_evento: string;
            /** Unidade Destino Id */
            unidade_destino_id: string | null;
            /** Unidade Origem Id */
            unidade_origem_id: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Service
             * @example api
             */
            service: string;
            /**
             * Status
             * @example ok
             */
            status: string;
        };
        /** HistoricoResponse */
        HistoricoResponse: {
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Eventos */
            eventos?: components["schemas"]["EventoHistoricoResponse"][];
            /** Mensagem Vazio */
            mensagem_vazio?: string | null;
            /** Processo Id */
            processo_id: string;
        };
        /** InteressadoInput */
        InteressadoInput: {
            /** Documento */
            documento?: string | null;
            /** Nome */
            nome: string;
            /** Tipo Documento */
            tipo_documento?: ("cpf" | "cnpj") | null;
            /** Tipo Participacao */
            tipo_participacao?: ("requerente" | "representado" | "terceiro") | null;
        };
        /** InteressadoResponse */
        InteressadoResponse: {
            /** Documento */
            documento: string | null;
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /** Tipo Documento */
            tipo_documento: string | null;
            /** Tipo Participacao */
            tipo_participacao: string | null;
        };
        /** KanbanResponse */
        KanbanResponse: {
            /** Items */
            items: components["schemas"]["CardProcessoResponse"][];
            /** Mensagem Vazio */
            mensagem_vazio?: string | null;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ListaUsuariosResponse */
        ListaUsuariosResponse: {
            /** Items */
            items: components["schemas"]["UsuarioResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Senha */
            senha: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * Exp
             * Format: date-time
             */
            exp: string;
            /** Token */
            token: string;
            usuario: components["schemas"]["UsuarioResumo"];
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Exp
             * Format: date-time
             */
            exp: string;
            usuario: components["schemas"]["UsuarioResumo"];
        };
        /** MensagemResponse */
        MensagemResponse: {
            /** Mensagem */
            mensagem: string;
        };
        /**
         * MeuPerfilResponse
         * @description US 1.5 — dados cadastrais + histórico de atuação. `processos` passa a
         *     listar os processos em que o usuário atuou (número, assunto, data e tipo de
         *     ação — US 1.5 Cen.1); `documentos_assinados` segue vazio até o Épico 3/4.
         *     As mensagens cobrem os estados vazios (Cen.2).
         */
        MeuPerfilResponse: {
            /** Documentos Assinados */
            documentos_assinados?: {
                [key: string]: unknown;
            }[];
            /**
             * Mensagem Documentos
             * @default Nenhum documento assinado
             */
            mensagem_documentos: string;
            /**
             * Mensagem Processos
             * @default Nenhum processo registrado
             */
            mensagem_processos: string;
            /** Processos */
            processos?: {
                [key: string]: unknown;
            }[];
            usuario: components["schemas"]["UsuarioResponse"];
        };
        /** PrimeiroAcessoRequest */
        PrimeiroAcessoRequest: {
            /** Senha */
            senha: string;
        };
        /**
         * ProcessoResponse
         * @description Saída completa de um processo (criação e detalhe).
         */
        ProcessoResponse: {
            /** Assunto */
            assunto: string;
            /** Concluido Em */
            concluido_em: string | null;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
            /** Criado Por Id */
            criado_por_id: string;
            /** Id */
            id: string;
            /** Interessados */
            interessados?: components["schemas"]["InteressadoResponse"][];
            /** Numero */
            numero: string;
            /** Ordem Atual */
            ordem_atual: number;
            /** Prazo Dias */
            prazo_dias: number;
            /**
             * Prazo Em
             * Format: date
             */
            prazo_em: string;
            /** Roteiro Id */
            roteiro_id: string;
            /** Status */
            status: string;
            /** Tipo Processo Id */
            tipo_processo_id: string;
            /** Unidade Atual Id */
            unidade_atual_id: string;
            /** Unidade Origem Id */
            unidade_origem_id: string;
        };
        /** RecuperarSenhaRequest */
        RecuperarSenhaRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** RedefinirSenhaRequest */
        RedefinirSenhaRequest: {
            /** Senha */
            senha: string;
        };
        /** RoteiroResponse */
        RoteiroResponse: {
            /** Etapas */
            etapas: components["schemas"]["EtapaRoteiroResponse"][];
            /** Id */
            id: string;
            /** Vigente */
            vigente: boolean;
        };
        /** SetupAdministrador */
        SetupAdministrador: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Nome */
            nome: string;
            /** Senha */
            senha: string;
        };
        /** SetupRequest */
        SetupRequest: {
            administrador: components["schemas"]["SetupAdministrador"];
            unidade: components["schemas"]["SetupUnidade"];
        };
        /** SetupResponse */
        SetupResponse: {
            /** Unidade Id */
            unidade_id: string;
            /** Usuario Id */
            usuario_id: string;
        };
        /** SetupStatusResponse */
        SetupStatusResponse: {
            /** Inicializado */
            inicializado: boolean;
        };
        /** SetupUnidade */
        SetupUnidade: {
            /** Nome */
            nome: string;
            /** Sigla */
            sigla: string;
        };
        /** TipoProcessoResponse */
        TipoProcessoResponse: {
            /** Ativo */
            ativo: boolean;
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            roteiro: components["schemas"]["RoteiroResponse"];
        };
        /** TransferirUnidadeRequest */
        TransferirUnidadeRequest: {
            /** Unidade Id */
            unidade_id: string;
        };
        /** TrocarSenhaRequest */
        TrocarSenhaRequest: {
            /** Nova Senha */
            nova_senha: string;
            /** Senha Atual */
            senha_atual: string;
        };
        /** UnidadeResponse */
        UnidadeResponse: {
            /** Ativo */
            ativo: boolean;
            /** Gestor Responsavel Id */
            gestor_responsavel_id: string | null;
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /** Sigla */
            sigla: string;
        };
        /** UnidadesGeridasRequest */
        UnidadesGeridasRequest: {
            /** Unidade Ids */
            unidade_ids: string[];
        };
        /** UsuarioResponse */
        UsuarioResponse: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /** Perfil */
            perfil: string;
            /** Status */
            status: string;
            /** Unidade Id */
            unidade_id: string | null;
        };
        /** UsuarioResumo */
        UsuarioResumo: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Nome */
            nome: string;
            /** Perfil */
            perfil: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resetar_senha_admin_admin_usuarios__usuario_id__resetar_senha_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensagemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensagemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    primeiro_acesso_auth_primeiro_acesso__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrimeiroAcessoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recuperar_senha_auth_recuperar_senha_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecuperarSenhaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensagemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redefinir_senha_auth_redefinir_senha__token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedefinirSenhaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensagemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trocar_senha_auth_trocar_senha_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrocarSenhaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MensagemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listar_emails_internal_dev_emails_get: {
        parameters: {
            query?: {
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevEmailItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resetar_internal_dev_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    process_email_task_internal_tasks_email_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailTaskPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_kanban_processos_get: {
        parameters: {
            query?: {
                filtro_unidade?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KanbanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_processo_processos_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarProcessoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_processos_processos_busca_get: {
        parameters: {
            query?: {
                numero?: string | null;
                assunto?: string | null;
                data_inicial?: string | null;
                data_final?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KanbanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalhe_processo_processos__processo_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                processo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    despachar_processo_processos__processo_id__despachar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                processo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DespacharRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    devolver_processo_processos__processo_id__devolver_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                processo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevolverRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historico_processo_processos__processo_id__historico_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                processo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inicializar_sistema_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_inicializacao_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    listar_tipos_processo_tipos_processo_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoProcessoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_tipo_processo_tipos_processo_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriarTipoProcessoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoProcessoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_roteiro_tipos_processo__tipo_processo_id__roteiro_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tipo_processo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtualizarRoteiroRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoteiroResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_unidades_unidades_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cadastrar_unidade_unidades_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadastroUnidadeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    editar_unidade_unidades__unidade_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                unidade_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarUnidadeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desativar_unidade_unidades__unidade_id__desativar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                unidade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_usuarios_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaUsuariosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cadastrar_usuario_usuarios_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadastroUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meu_perfil_usuarios_me_perfil_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeuPerfilResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transferir_unidade_usuarios__usuario_id__unidade_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferirUnidadeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_unidades_geridas_usuarios__usuario_id__unidades_geridas_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    definir_unidades_geridas_usuarios__usuario_id__unidades_geridas_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                usuario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnidadesGeridasRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
